from functions2 import Baum_Welch, forward_HMM, backward_HMM, compute_all_conditional
import numpy as np

A = np.array([[0.6, 0.4], [0.3, 0.7]])
B = np.array([[0.5, 0.5], [0.1, 0.9]])
pi = np.array([0.2, 0.8])
observed = np.array([1, 0, 1])
B_start = np.zeros((2, 2)) + 0.5

alpha, c = forward_HMM(A, B, pi, observed)
beta_hat, beta = backward_HMM(A, B, observed, c)
gamma = compute_all_conditional(alpha, beta)


# text experiment


In [1]:
import random
from src.CipherUtils import CipherGenerator
from src.CipherUtils import TextDecoder, TextEncoder


hidden_sequence = "people of western europe a landing was made this morning on the coast of france by troops kangaroo jokes quasi vile xilophone zenit "
hidden_sequence = " in germany it seems to be pretty much automatic pretty much all the time in france and spain it all depends presumably on social subtleties that you have to be french or spanish to understand in italy why would you even bother when and how much to tip is a question that has been vexing visitors to europe for as long as people have been travelling around the continent outside their own country it seems even europeans don t know the answer according to new polling by yougov in six eu countries britain and the us where as most visitors know but may be reluctant to acknowledge gratuities may make up more than half your waitperson s income europeans are deeply divided on tipping in restaurants for example of respondents in germany told the pollster they typically tipped almost the same as the us in the uk where an optional service charge of about is usually included said they left a gratuity the figure in spain where service is often included in restaurant bills but diners can leave optional tips was while in france where every price on a restaurant menu already includes for service of people said they generally tipped on top even in sweden where tips are generally not expected the figure was but only of italians said they would typically leave a gratuity after a meal out with a rather greater proportion admitting they never left a cent a startling of respondents in the us however and of germans by far the most in europe confessed they would tip sometimes or often even if the service was terrible indicating that for some tipping is not about quality of service at all the findings of the survey will come as a surprise in germany a country that does not generally think of itself as a nation of happy distributors of the word in a similar vein to pourboire in french means drinking money"
# hidden_sequence = " hello banana xilophone key queue zebra cock pussy tits dandy fart though jolly world mum "

cipher_generator = CipherGenerator()
cipher = cipher_generator.generate_cipher()
encoder = TextEncoder()
observed_sequence = encoder.encode_text(hidden_sequence, cipher=cipher)


print(observed_sequence)

 fn sdxzinl fy jddzj yc pd rxdyyl zwvh iwycziyfv rxdyyl zwvh ikk yhd yfzd fn exinvd inq jrifn fy ikk qdrdnqj rxdjwzipkl cn jcvfik jwpykdyfdj yhiy lcw hitd yc pd exdnvh cx jrinfjh yc wnqdxjyinq fn fyikl ahl acwkq lcw dtdn pcyhdx ahdn inq hca zwvh yc yfr fj i owdjyfcn yhiy hij pddn tdmfns tfjfycxj yc dwxcrd ecx ij kcns ij rdcrkd hitd pddn yxitdkkfns ixcwnq yhd vcnyfndny cwyjfqd yhdfx can vcwnyxl fy jddzj dtdn dwxcrdinj qcn y unca yhd injadx ivvcxqfns yc nda rckkfns pl lcwsct fn jfm dw vcwnyxfdj pxfyifn inq yhd wj ahdxd ij zcjy tfjfycxj unca pwy zil pd xdkwvyiny yc ivuncakdqsd sxiywfyfdj zil ziud wr zcxd yhin hike lcwx aifyrdxjcn j fnvczd dwxcrdinj ixd qddrkl qftfqdq cn yfrrfns fn xdjyiwxinyj ecx dmizrkd ce xdjrcnqdnyj fn sdxzinl yckq yhd rckkjydx yhdl ylrfvikkl yfrrdq ikzcjy yhd jizd ij yhd wj fn yhd wu ahdxd in cryfcnik jdxtfvd vhixsd ce ipcwy fj wjwikkl fnvkwqdq jifq yhdl kdey i sxiywfyl yhd efswxd fn jrifn ahdxd jdxtfvd fj ceydn fnvkwqdq fn xdjyiwxiny pfkkj pwy qfndxj vin kditd cryfcn

In [2]:
from prove.src.Probability import ProbabilityMatrix

with open("texts/moby_dick.txt", "r") as file:
    text = file.read()

alphabet = list("abcdefghijklmnopqrstuvwxyz ")


pm = ProbabilityMatrix(text=text, alphabet=alphabet)
unknown_chars = pm.unknown_chars()
pm.preprocess_text(unknown_chars=unknown_chars)

# compute probabilities
pm.compute_matrix_spaces()

In [23]:
from src.ProbabilityMatrix import ProbabilityMatrix
from src.CipherUtils import TextPreProcessor

preprocess = TextPreProcessor()
text = preprocess.lower(text)
text = preprocess.remove_additional_spaces(text)
text = preprocess.remove_unknown_chars(
    text=text, unknown_chars=preprocess.unknown_chars(text)
)

probability = ProbabilityMatrix(text=text)
probability.compute_probability_table()

In [28]:
table = probability.probability_table
sorted_dict = dict(sorted(table.items(), key=lambda x: x[0]))

sorted_dict

{'  ': 0.03322369139801031,
 ' a': 0.01974983486479082,
 ' b': 0.009381192570344237,
 ' c': 0.007032322801096532,
 ' d': 0.004889346804108463,
 ' e': 0.003292619590666373,
 ' f': 0.006946603761217009,
 ' g': 0.002945541517428698,
 ' h': 0.011537614691234975,
 ' i': 0.012126722994720715,
 ' j': 0.0007050811221462703,
 ' k': 0.000799203989464962,
 ' l': 0.005111207848502522,
 ' m': 0.007049970838718786,
 ' n': 0.0040279544915936515,
 ' o': 0.011720818129408858,
 ' p': 0.005078432921489763,
 ' q': 0.0006017140446444929,
 ' r': 0.003248079305238778,
 ' s': 0.016703447418092095,
 ' t': 0.029631055167765607,
 ' u': 0.002213568147477087,
 ' v': 0.001323602821669101,
 ' w': 0.012156976773501724,
 ' x': 4.2019137195844475e-06,
 ' y': 0.002100116477048307,
 ' z': 2.8573013293174242e-05,
 'a ': 0.004604457053920637,
 'aa': 3.361530975667558e-06,
 'ab': 0.0016471501780771034,
 'ac': 0.0020051532269856984,
 'ad': 0.002616111481813277,
 'ae': 4.3699902683678256e-05,
 'af': 0.0005201969184845546,
 'a

In [16]:
transition_probs = pm.matrix
transition_probs

array([[3.36153098e-06, 7.91640545e-04, 2.62871722e-03, 9.15176808e-04,
        5.29945358e-03, 9.95853552e-04, 9.52994032e-04, 9.53330185e-03,
        8.12650113e-04, 1.81522673e-04, 3.52960752e-05, 3.00941061e-03,
        3.29430036e-03, 1.31772014e-03, 1.06308417e-03, 1.50680626e-03,
        0.00000000e+00, 2.84301482e-03, 1.79925945e-03, 2.90352238e-03,
        4.24393286e-04, 6.18521700e-04, 3.25564275e-03, 7.56344470e-05,
        2.29424489e-04, 4.11787545e-05, 1.97498349e-02],
       [1.64715018e-03, 3.50439604e-04, 0.00000000e+00, 2.52114823e-06,
        1.33620856e-04, 0.00000000e+00, 2.52114823e-06, 1.42865066e-05,
        4.30275965e-04, 0.00000000e+00, 5.04229646e-06, 4.03383717e-05,
        3.89097210e-04, 3.10941615e-05, 4.63891275e-04, 5.88267921e-06,
        0.00000000e+00, 3.73129938e-04, 1.93288031e-05, 5.88267921e-06,
        6.31127441e-04, 0.00000000e+00, 1.68076549e-06, 0.00000000e+00,
        1.93288031e-05, 2.52114823e-06, 9.38119257e-03],
       [2.00515323e-03

In [4]:
def map_alphabet_to_numbers():
    alphabet = "abcdefghijklmnopqrstuvwxyz "
    mapping = {char: i for i, char in enumerate(alphabet)}
    return mapping

In [5]:
def translate_string_to_numbers(text, mapping):
    numbers = [mapping[char] for char in text]
    return numbers

In [6]:
hidden_ = translate_string_to_numbers(
    hidden_sequence, mapping=map_alphabet_to_numbers()
)
observed_ = translate_string_to_numbers(
    observed_sequence, mapping=map_alphabet_to_numbers()
)

In [17]:
from functions2 import forward_HMM
import numpy as np

a, ah, c = forward_HMM(
    A=transition_probs,
    B=np.zeros((27, 27)) + 1 / 27,
    pi=transition_probs[-1, :],
    observed=observed_,
)

/Users/michelealessi/Desktop/HMM-for-text-decryption/functions2.py:34: RuntimeWarning: invalid value encountered in divide
  alpha_hat[i] = alpha[i] / np.sum(alpha[i])
/Users/michelealessi/Desktop/HMM-for-text-decryption/functions2.py:33: RuntimeWarning: invalid value encountered in double_scalars
  c[i] = np.sum(alpha[i]) / np.prod(c[0:i])


In [20]:
print(a)

[[1.70535446e-04 2.85730133e-05 1.30103699e-05 ... 3.76242467e-04
  3.42378155e-07 1.23050709e-03]
 [1.13636862e-06 2.75502400e-07 2.78899456e-07 ... 5.61363452e-07
  1.33716233e-08 3.83576028e-06]
 [3.09676891e-09 7.25947258e-10 9.06714118e-10 ... 1.67571661e-09
  3.32374174e-11 1.15660244e-08]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [19]:
ah

array([[2.15533858e-02, 3.61124442e-03, 1.64433570e-03, ...,
        4.75519854e-02, 4.32719920e-05, 1.55519539e-01],
       [4.95029732e-02, 1.20015528e-02, 1.21495368e-02, ...,
        2.44543535e-02, 5.82500344e-04, 1.67095021e-01],
       [4.65687560e-02, 1.09166883e-02, 1.36350337e-02, ...,
        2.51991802e-02, 4.99819402e-04, 1.73928177e-01],
       ...,
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan],
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan],
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan]])

In [13]:
c

array([0.00791223, 0.00290127, 0.00289685, ...,        nan,        nan,
              nan])

In [8]:
from functions2 import backward_HMM

b, bh = backward_HMM(
    A=pm.matrix, B=np.zeros((27, 27)) + 1 / 27, observed=observed_, c=c
)

In [9]:
bh

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [10]:
from functions2 import Baum_Welch
import numpy as np

emission = Baum_Welch(
    A=pm.matrix,
    B_start=np.zeros((27, 27)) + 1 / 27,
    pi=pm.matrix[-1, :],
    observed=observed_,
    maxIter=1000,
)

KeyboardInterrupt: 

In [17]:
emission.argmax(axis=1)

array([18, 22, 18,  3,  2,  0, 12,  6,  6, 18, 25, 14,  0, 24, 11, 25, 11,
       24, 25,  4, 24, 25,  4, 26, 10, 14, 26])