from functions2 import Baum_Welch, forward_HMM, backward_HMM, compute_all_conditional
import numpy as np

A = np.array([[0.6, 0.4], [0.3, 0.7]])
B = np.array([[0.5, 0.5], [0.1, 0.9]])
pi = np.array([0.2, 0.8])
observed = np.array([1, 0, 1])
B_start = np.zeros((2, 2)) + 0.5

alpha, c = forward_HMM(A, B, pi, observed)
beta_hat, beta = backward_HMM(A, B, observed, c)
gamma = compute_all_conditional(alpha, beta)


# text experiment


In [1]:
import random
from src.CipherUtils import CipherGenerator
from src.CipherUtils import TextDecoder, TextEncoder


hidden_sequence = "people of western europe a landing was made this morning on the coast of france by troops kangaroo jokes quasi vile xilophone zenit "
hidden_sequence = " in germany it seems to be pretty much automatic pretty much all the time in france and spain it all depends presumably on social subtleties that you have to be french or spanish to understand in italy why would you even bother when and how much to tip is a question that has been vexing visitors to europe for as long as people have been travelling around the continent outside their own country it seems even europeans don t know the answer according to new polling by yougov in six eu countries britain and the us where as most visitors know but may be reluctant to acknowledge gratuities may make up more than half your waitperson s income europeans are deeply divided on tipping in restaurants for example of respondents in germany told the pollster they typically tipped almost the same as the us in the uk where an optional service charge of about is usually included said they left a gratuity the figure in spain where service is often included in restaurant bills but diners can leave optional tips was while in france where every price on a restaurant menu already includes for service of people said they generally tipped on top even in sweden where tips are generally not expected the figure was but only of italians said they would typically leave a gratuity after a meal out with a rather greater proportion admitting they never left a cent a startling of respondents in the us however and of germans by far the most in europe confessed they would tip sometimes or often even if the service was terrible indicating that for some tipping is not about quality of service at all the findings of the survey will come as a surprise in germany a country that does not generally think of itself as a nation of happy distributors of the word in a similar vein to pourboire in french means drinking money"
# hidden_sequence = " hello banana xilophone key queue zebra cock pussy tits dandy fart though jolly world mum "


cipher_generator = CipherGenerator()
cipher = cipher_generator.generate_cipher()
encoder = TextEncoder()
observed_sequence = encoder.encode_text(hidden_sequence, cipher=cipher)


print(observed_sequence)

 mp hjiqvpn ml yjjqy lc fj oijlln qart valcqvlmr oijlln qart vee ltj lmqj mp xivprj vpw yovmp ml vee wjojpwy oijyaqvfen cp ycrmve yaflejlmjy ltvl nca tvsj lc fj xijprt ci yovpmyt lc apwjiylvpw mp mlven dtn dcaew nca jsjp fcltji dtjp vpw tcd qart lc lmo my v kajylmcp ltvl tvy fjjp sjgmph smymlciy lc jaicoj xci vy ecph vy ojcoej tvsj fjjp livsjeemph vicapw ltj rcplmpjpl calymwj ltjmi cdp rcaplin ml yjjqy jsjp jaicojvpy wcp l zpcd ltj vpydji vrrciwmph lc pjd oceemph fn ncahcs mp ymg ja rcaplimjy fimlvmp vpw ltj ay dtjij vy qcyl smymlciy zpcd fal qvn fj ijearlvpl lc vrzpcdejwhj hivlamlmjy qvn qvzj ao qcij ltvp tvex ncai dvmlojiycp y mprcqj jaicojvpy vij wjjoen wmsmwjw cp lmoomph mp ijylvaivply xci jgvqoej cx ijyocpwjply mp hjiqvpn lcew ltj oceeylji ltjn lnomrveen lmoojw veqcyl ltj yvqj vy ltj ay mp ltj az dtjij vp colmcpve yjismrj rtvihj cx vfcal my ayaveen mpreawjw yvmw ltjn ejxl v hivlamln ltj xmhaij mp yovmp dtjij yjismrj my cxljp mpreawjw mp ijylvaivpl fmeey fal wmpjiy rvp ejvsj colmcp

In [2]:
from prove.src.Probability import ProbabilityMatrix

with open("texts/moby_dick.txt", "r") as file:
    text = file.read()

alphabet = list("abcdefghijklmnopqrstuvwxyz ")


pm = ProbabilityMatrix(text=text, alphabet=alphabet)
unknown_chars = pm.unknown_chars()
pm.preprocess_text(unknown_chars=unknown_chars)

# compute probabilities
pm.compute_matrix_spaces()

# classe usata per MCMC qui in teori non serve piu

from src.ProbabilityMatrix import ProbabilityMatrix
from src.CipherUtils import TextPreProcessor

preprocess = TextPreProcessor()
text = preprocess.lower(text)
text = preprocess.remove_additional_spaces(text)
text = preprocess.remove_unknown_chars(
text=text, unknown_chars=preprocess.unknown_chars(text)
)

probability = ProbabilityMatrix(text=text)
probability.compute_probability_table()


In [3]:
def map_alphabet_to_numbers():
    alphabet = "abcdefghijklmnopqrstuvwxyz "
    mapping = {char: i for i, char in enumerate(alphabet)}
    return mapping

In [4]:
def translate_string_to_numbers(text, mapping):
    numbers = [mapping[char] for char in text]
    return numbers

In [5]:
hidden_ = translate_string_to_numbers(
    hidden_sequence, mapping=map_alphabet_to_numbers()
)
observed_ = translate_string_to_numbers(
    observed_sequence, mapping=map_alphabet_to_numbers()
)

In [6]:
transition_probs = pm.matrix

In [7]:
from functions2 import forward_HMM
import numpy as np

ah, c = forward_HMM(
    A=transition_probs,
    B=np.zeros((27, 27)) + 1 / 27,
    pi=transition_probs[-1, :],
    observed=observed_,
)

In [8]:
ah.sum(axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [9]:
from functions2 import backward_HMM

bh = backward_HMM(A=pm.matrix, B=np.zeros((27, 27)) + 1 / 27, observed=observed_, c=c)

In [10]:
bh.sum(axis=1)

array([15.13592885, 13.55682443, 13.44579442, ..., 13.47509856,
       13.44227918, 12.50348472])

In [11]:
from functions2 import Baum_Welch
import numpy as np

emission = Baum_Welch(
    A=pm.matrix,
    B_start=np.zeros((27, 27)) + 1 / 27,
    pi=pm.matrix[-1, :],
    observed=observed_,
    maxIter=800,
)

In [14]:
emission

array([[7.93155271e-002, 0.00000000e+000, 5.67676261e-002,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        8.47370244e-084, 0.00000000e+000, 0.00000000e+000,
        6.98983560e-003, 0.00000000e+000, 1.61939185e-158,
        0.00000000e+000, 2.78957369e-318, 0.00000000e+000,
        6.53900419e-260, 0.00000000e+000, 0.00000000e+000,
        8.33093800e-001, 0.00000000e+000, 5.34305459e-220,
        0.00000000e+000, 2.38332111e-002, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 7.27921205e-311, 7.85725378e-001,
        0.00000000e+000, 1.28247931e-001, 0.00000000e+000,
        8.60266910e-002, 1.28854630e-191, 0.00000000e+000,
        0.00000000e+000, 5.78405771e-038, 1.94877905e-309,
        9.69186544e-144, 1.34651760e-031, 1.85472243e-320,
        6.81303538e-152, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.15701917e-162, 0.00000000e+0

In [16]:
emission.argmax(axis=1)

array([21,  5, 17, 22,  9, 23,  7, 19, 12, 13, 18,  4, 16, 15,  2,  5,  9,
        8, 24, 11,  0, 18,  3, 13, 13, 25, 26])