In [8]:
import numpy as np


def compute_f(A, B, observed):
    n_nodes = len(observed)
    n_states = A.shape[0]
    f = np.zeros((n_nodes - 1, n_states, n_states))

    for i in range(n_nodes - 1):
        tmp = np.zeros((n_states, n_states))
        for j in range(n_states):
            for k in range(n_states):
                tmp[j, k] = A[j, k] * B[k, observed[i + 1]]
        f[i] = tmp

    return f

In [50]:
A = np.array([[0.3, 0.7], [0.9, 0.1]])
B = np.array([[0.2, 0.8], [0.5, 0.5]])
observed = np.array([0, 1, 1])
compute_f(A, B, observed)

array([[[0.24, 0.35],
        [0.72, 0.05]],

       [[0.24, 0.35],
        [0.72, 0.05]]])

In [64]:
def Viterbi(A, B, observed):
    n_nodes = len(observed)
    n_states = A.shape[0]

    pmax = np.zeros((n_nodes - 1, n_states))
    phi = np.zeros((n_nodes - 1, n_states))

    f = compute_f(A, B, observed)

    pmax[0] = np.max(np.log(f[0]), axis=0)
    phi[0] = np.argmax(f[0], axis=0)

    for i in range(1, n_nodes - 1):
        tmp = (np.log(f[i]).T + pmax[i-1]).T

        pmax[i] = np.max(tmp, axis=0)
        
        phi[i] = np.argmax(tmp, axis=0)

    return pmax, phi

In [65]:
Viterbi(A, B, observed)

(array([[-0.32850407, -1.04982212],
        [-1.37832619, -1.37832619]]),
 array([[1., 0.],
        [1., 0.]]))