In [ ]:
def reconstruct(pmax, phi):
    """
    Ricostruisce tutti i most probable, per ora fa schifo ma sembra funzionare, da ricontrollare
    """
    reconstruction = np.empty(len(phi)+1)

    curr = np.argmax(pmax[-1])
    reconstruction[-1] = curr

    for i in range(len(phi)-1, -1, -1):
        curr = int(phi[i, curr])
        reconstruction[i] = curr
    
    return reconstruction

### Experiement with matrix like the one we have (last row of spaces has 1)

In [10]:
A = np.array([[0.1, 0.8, 0.1],
              [0.8, 0.1, 0.1],
              [0.5, 0.5, 0]])

B = np.array([[0.8, 0.2, 0],
              [0.2, 0.8, 0],
              [0, 0, 1]])

observed = np.array([0, 2, 1])

In [11]:
def compute_f(A, B, observed):
    """
    Careful when handling
    - f0 is the first message (from first factor to node, it is just a vector) 
    - f contains all other factors evaluated
    """
    pi = A[-1]
    n_nodes = len(observed)
    n_states = A.shape[0]
    f = np.zeros((n_nodes-1, n_states, n_states))
    
    tmp = np.zeros((n_states, 1))
    for k in range(n_states):
        tmp[k] = pi[k] * B[k, observed[0]]
    
    f0 = tmp

    for i in range(1, n_nodes):
        tmp = np.zeros((n_states, n_states))
        
        for j in range(n_states): # over z1
            
            for k in range(n_states): # over z2
                tmp[j, k] = A[j, k] * B[k, observed[i]]
        
        f[i-1] = tmp
    

    return f0, f

In [12]:
f0, f = compute_f(A, B, observed)
print("f0:\n", f0, "\nf:\n", f)

f0:
 [[0.4]
 [0.1]
 [0. ]] 
f:
 [[[0.   0.   0.1 ]
  [0.   0.   0.1 ]
  [0.   0.   0.  ]]

 [[0.02 0.64 0.  ]
  [0.16 0.08 0.  ]
  [0.1  0.4  0.  ]]]


In [13]:
def Viterbi(f0, f):
    n_nodes = f.shape[0] + 1
    n_states = f.shape[1]

    pmax = np.zeros((n_nodes, n_states))    # Need one for every node
    phi = np.zeros((n_nodes - 1, n_states)) # Need one for every node other than the first one (no need to reconstruct it)

    pmax[0] = f0.flatten()

    for i in range(1, n_nodes):
        tmp = ((f[i-1]).T * pmax[i - 1]).T

        pmax[i] = np.max(tmp, axis=0) # by column

        phi[i-1] = np.argmax(tmp, axis=0) # i-1 cause this contains the reconstruction about the (i-1)th element

    return pmax, phi

In [15]:
pmax, phi = Viterbi(f0, f)
print("pmax:\n", pmax, "\nphi:\n", phi)

print("\nReconstruction using Viterbi:\n", reconstruct(pmax, phi))

pmax:
 [[0.4   0.1   0.   ]
 [0.    0.    0.04 ]
 [0.004 0.016 0.   ]] 
phi:
 [[0. 0. 0.]
 [2. 2. 0.]]

Reconstruction using Viterbi:
 [0. 2. 1.]


In [16]:
observed = np.array([0, 2, 1, 0, 2, 0, 1, 0, 2, 1, 0, 1, 0]) # a _ b a
f0, f = compute_f(A, B, observed)
pmax, phi = Viterbi(f0, f)
print("pmax:\n", pmax, "\nphi:\n", phi)

print("\nReconstruction using Viterbi:\n", reconstruct(pmax, phi))

pmax:
 [[4.00000000e-01 1.00000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.00000000e-02]
 [4.00000000e-03 1.60000000e-02 0.00000000e+00]
 [1.02400000e-02 6.40000000e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.02400000e-03]
 [4.09600000e-04 1.02400000e-04 0.00000000e+00]
 [1.63840000e-05 2.62144000e-04 0.00000000e+00]
 [1.67772160e-04 5.24288000e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.67772160e-05]
 [1.67772160e-06 6.71088640e-06 0.00000000e+00]
 [4.29496730e-06 2.68435456e-07 0.00000000e+00]
 [8.58993459e-08 2.74877907e-06 0.00000000e+00]
 [1.75921860e-06 5.49755814e-08 0.00000000e+00]] 
phi:
 [[0. 0. 0.]
 [2. 2. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [2. 2. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]
 [2. 2. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]

Reconstruction using Viterbi:
 [0. 2. 1. 0. 2. 0. 1. 0. 2. 1. 0. 1. 0.]


# Log computations
Now we need to find a way for this to hold even when working with logs.
I suspect that replacing with the minimum to account for the 0 is too big, we need something smaller.

In [17]:
A = np.array([[0.1, 0.8, 0.1],
              [0.8, 0.1, 0.1],
              [0.5, 0.5, 0]])

B = np.array([[0.8, 0.2, 0],
              [0.2, 0.8, 0],
              [0, 0, 1]])

observed = np.array([0, 2, 1])

In [18]:
def compute_f_log(A, B, observed):
    """
    Even though it contains the -inf, this is fine, as that means we should not reconstruct using those (?)
    """
    pi = A[-1]
    n_nodes = len(observed)
    n_states = A.shape[0]
    f = np.zeros((n_nodes-1, n_states, n_states))
    
    tmp = np.zeros((n_states, 1))
    for k in range(n_states):
        tmp[k] = np.log(pi[k]) + np.log(B[k, observed[0]])
    
    f0 = tmp

    for i in range(1, n_nodes):
        tmp = np.zeros((n_states, n_states))
        
        for j in range(n_states): # over z1
            
            for k in range(n_states): # over z2
                tmp[j, k] = np.log(A[j, k]) + np.log(B[k, observed[i]])
    
        f[i-1] = tmp
    

    return f0, f

In [19]:
def Viterbi_log(f0, f):
    n_nodes = f.shape[0] + 1
    n_states = f.shape[1]

    pmax = np.zeros((n_nodes, n_states))    # Need one for every node
    phi = np.zeros((n_nodes - 1, n_states)) # Need one for every node other than the first one (no need to reconstruct it)

    pmax[0] = f0.flatten()

    for i in range(1, n_nodes):
        tmp = ((f[i-1]).T + pmax[i - 1]).T

        pmax[i] = np.max(tmp, axis=0) # by column

        phi[i-1] = np.argmax(tmp, axis=0) # i-1 cause this contains the reconstruction about the (i-1)th element

    return pmax, phi

In [20]:
f0, f = compute_f_log(A, B, observed)
print("f0:\n", f0, "\nf:\n", f)


pmax, phi = Viterbi_log(f0, f)
print("\n\npmax:\n", pmax, "\nphi:\n", phi)

print("\n\n reconstruction:", reconstruct(pmax, phi))

f0:
 [[-0.91629073]
 [-2.30258509]
 [       -inf]] 
f:
 [[[       -inf        -inf -2.30258509]
  [       -inf        -inf -2.30258509]
  [       -inf        -inf        -inf]]

 [[-3.91202301 -0.4462871         -inf]
  [-1.83258146 -2.52572864        -inf]
  [-2.30258509 -0.91629073        -inf]]]


pmax:
 [[-0.91629073 -2.30258509        -inf]
 [       -inf        -inf -3.21887582]
 [-5.52146092 -4.13516656        -inf]] 
phi:
 [[0. 0. 0.]
 [2. 2. 0.]]


 reconstruction: [0. 2. 1.]


/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:12: RuntimeWarning: divide by zero encountered in log
  tmp[k] = np.log(pi[k]) + np.log(B[k, observed[0]])
/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:22: RuntimeWarning: divide by zero encountered in log
  tmp[j, k] = np.log(A[j, k]) + np.log(B[k, observed[i]])


In [21]:
observed = np.array([0, 2, 1, 2, 1, 0, 1]) # a = 0; b = 1; _ = 2
f0, f = compute_f_log(A, B, observed)
print("f0:\n", f0, "\nf:\n", f)


pmax, phi = Viterbi_log(f0, f)
print("\n\npmax:\n", pmax, "\nphi:\n", phi)

print("\n\n reconstruction:", reconstruct(pmax, phi))

f0:
 [[-0.91629073]
 [-2.30258509]
 [       -inf]] 
f:
 [[[       -inf        -inf -2.30258509]
  [       -inf        -inf -2.30258509]
  [       -inf        -inf        -inf]]

 [[-3.91202301 -0.4462871         -inf]
  [-1.83258146 -2.52572864        -inf]
  [-2.30258509 -0.91629073        -inf]]

 [[       -inf        -inf -2.30258509]
  [       -inf        -inf -2.30258509]
  [       -inf        -inf        -inf]]

 [[-3.91202301 -0.4462871         -inf]
  [-1.83258146 -2.52572864        -inf]
  [-2.30258509 -0.91629073        -inf]]

 [[-2.52572864 -1.83258146        -inf]
  [-0.4462871  -3.91202301        -inf]
  [-0.91629073 -2.30258509        -inf]]

 [[-3.91202301 -0.4462871         -inf]
  [-1.83258146 -2.52572864        -inf]
  [-2.30258509 -0.91629073        -inf]]]


pmax:
 [[ -0.91629073  -2.30258509         -inf]
 [        -inf         -inf  -3.21887582]
 [ -5.52146092  -4.13516656         -inf]
 [        -inf         -inf  -6.43775165]
 [ -8.74033674  -7.35404238        

/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:12: RuntimeWarning: divide by zero encountered in log
  tmp[k] = np.log(pi[k]) + np.log(B[k, observed[0]])
/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:22: RuntimeWarning: divide by zero encountered in log
  tmp[j, k] = np.log(A[j, k]) + np.log(B[k, observed[i]])


### Try using our words example
Now using the matrix and our phrase we try and see if it works

In [23]:
from src.CipherUtils import CipherGenerator
from src.CipherUtils import TextEncoder
from src.ProbabilityMatrix import ProbabilityMatrix
from src.CipherUtils import TextPreProcessor

from src.HMM_utils import map_alphabet_to_numbers, string_to_numbers
from src.HMM_utils import find_mapping, numbers_to_string, invert_mapping

from src.HMM_functions import Baum_Welch

In [87]:
#hidden_sequence = "people of western europe a landing was made this morning on the coast of france by troops kangaroo jokes quasi vile xilophone zenit "
hidden_sequence = "in germany it seems to be pretty much automatic pretty much all the time in france and spain it all just depends presumably on social subtleties that you have to be french or spanish to understand in italy why would you even just bother when and how much to tip is a question that has been vexing visitors to europe for as long as people have been travelling around the continent outside their own country it seems even europeans don t know the answer according to new polling by yougov in six eu countries britain and the us where as most visitors know but may be reluctant to acknowledge gratuities may make up more than half your waitperson s income europeans are deeply divided on tipping in restaurants for example of respondents in germany told the pollster they typically tipped almost the same as the us in the uk where an optional service charge of about is usually included said they left a gratuity the figure in spain where service is often included in restaurant bills but diners can leave optional tips was while in france where every price on a restaurant menu already includes for service of people said they generally tipped on top even in sweden where tips are generally not expected the figure was but only of italians said they would typically leave a gratuity after a meal out with a rather greater proportion admitting they never left a cent a startling of respondents in the us however and of germans by far the most in europe confessed they would tip sometimes or often even if the service was terrible indicating that for some tipping is not about quality of service at all the findings of the survey will come as a surprise in germany a country that does not generally think of itself as a nation of happy distributors"
# hidden_sequence = "hello banana xilophone key queue zebra cock pussy tits dandy fart though jolly world mum "

cipher_generator = CipherGenerator()
cipher = cipher_generator.generate_cipher()
encoder = TextEncoder()
observed_sequence = encoder.encode_text(hidden_sequence, cipher=cipher)

# Convert to numeric
hidden_ = string_to_numbers(hidden_sequence, mapping=map_alphabet_to_numbers())
observed_ = string_to_numbers(observed_sequence, mapping=map_alphabet_to_numbers())

print(hidden_sequence)
print(observed_sequence)

in germany it seems to be pretty much automatic pretty much all the time in france and spain it all just depends presumably on social subtleties that you have to be french or spanish to understand in italy why would you even just bother when and how much to tip is a question that has been vexing visitors to europe for as long as people have been travelling around the continent outside their own country it seems even europeans don t know the answer according to new polling by yougov in six eu countries britain and the us where as most visitors know but may be reluctant to acknowledge gratuities may make up more than half your waitperson s income europeans are deeply divided on tipping in restaurants for example of respondents in germany told the pollster they typically tipped almost the same as the us in the uk where an optional service charge of about is usually included said they left a gratuity the figure in spain where service is often included in restaurant bills but diners can lea

In [88]:
# List of text file paths to build our corpus (where we learn the transitions probs)
file_paths = [
    "texts/moby_dick.txt",
    "texts/shakespeare.txt",
    "texts/james-joyce-a-portrait-of-the-artist-as-a-young-man.txt",
    "texts/james-joyce-dubliners.txt",
    "texts/james-joyce-ulysses.txt",
]

texts = []
for file_path in file_paths:
    with open(file_path, "r") as file:
        texts.append(file.read())

corpus = "".join(texts)
alphabet = list("abcdefghijklmnopqrstuvwxyz ")

preprocessor = TextPreProcessor()
corpus = preprocessor.lower(text=corpus)
corpus = preprocessor.remove_additional_spaces(text=corpus)
corpus = preprocessor.remove_unknown_chars(
    text=corpus, unknown_chars=preprocessor.unknown_chars(corpus)
)

# compute probabilities
p = ProbabilityMatrix(corpus)
p.compute_probability_matrix()
p.compute_normalized_matrix()
# p.compute_probability_table()

In [120]:
B_start = np.zeros((27, 27)) + 1 / 26
B_start[:, -1] = np.zeros(27)
B_start[-1, :] = np.zeros(27)
B_start[-1, -1] = 1

emission = Baum_Welch(
    A=p.normalized_matrix,
    B_start=B_start,
    pi=p.normalized_matrix[-1, :],
    observed=observed_,
    maxIter=50,
)
mapping = find_mapping(emission.argmax(axis=1))
normalized_emission_reconstruction = numbers_to_string(observed_sequence, invert_mapping(mapping))

In [121]:
B_start = np.zeros((27, 27)) + 1 / 26
B_start[:, -1] = np.zeros(27)
B_start[-1, :] = np.zeros(27)
B_start[-1, -1] = 1

emission_non_norm = Baum_Welch(
    A=p.probability_matrix,
    B_start=B_start,
    pi=p.probability_matrix[-1, :],
    observed=observed_,
    maxIter=50,
)
mapping_non_norm = find_mapping(emission_non_norm.argmax(axis=1))
non_normalized_emission_reconstruction = numbers_to_string(observed_sequence, invert_mapping(mapping_non_norm))

In [105]:
f0, f = compute_f_log(A = p.normalized_matrix, B=emission, observed=observed_)
pmax, phi = Viterbi_log(f0, f)
reconstruction = reconstruct(pmax, phi)
reconstruction = reconstruction.astype(int)

/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:12: RuntimeWarning: divide by zero encountered in log
  tmp[k] = np.log(pi[k]) + np.log(B[k, observed[0]])
/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:22: RuntimeWarning: divide by zero encountered in log
  tmp[j, k] = np.log(A[j, k]) + np.log(B[k, observed[i]])


In [106]:
f0, f = compute_f_log(A = p.probability_matrix, B=emission_non_norm, observed=observed_)
pmax, phi = Viterbi_log(f0, f)
reconstruction_non_norm = reconstruct(pmax, phi)
reconstruction_non_norm = reconstruction_non_norm.astype(int)

/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:12: RuntimeWarning: divide by zero encountered in log
  tmp[k] = np.log(pi[k]) + np.log(B[k, observed[0]])
/var/folders/tv/ysw0jsvs2t331mtk7hdh35kc0000gn/T/ipykernel_63233/3658002382.py:22: RuntimeWarning: divide by zero encountered in log
  tmp[j, k] = np.log(A[j, k]) + np.log(B[k, observed[i]])


In [96]:
import numpy as np

def convert_numbers_to_letters(numbers):
    letters = []
    for number in numbers:
        if number == 26:
            letters.append(' ')
        else:
            letter = chr(number + ord('a'))
            letters.append(letter)
    return ''.join(letters)


In [124]:
normalized_reconstruction = convert_numbers_to_letters(reconstruction)
non_normalized_reconstruction = convert_numbers_to_letters(reconstruction_non_norm)

print("Non-normalized emission reconstruction:\n", non_normalized_emission_reconstruction)
print("Non-normalized reconstruction:\n", non_normalized_reconstruction)

print("\n")

print("Normalized emission reconstruction:\n", normalized_emission_reconstruction)
print("Normalized reconstruction:\n", normalized_reconstruction)

Non-normalized emission reconstruction:
 in permany it seems to be qretty muzh automatiz qretty muzh all the time in franze and sqain it all qust deqends qresumably on sozial subtleties that you have to be frenzh or sqanish to understand in italy why would you even qust bother when and how muzh to tiq is a muestion that has been vexinp visitors to euroqe for as lonp as qeoqle have been travellinp around the zontinent outside their own zountry it seems even euroqeans don t rnow the answer azzordinp to new qollinp by youpov in six eu zountries britain and the us where as most visitors rnow but may be reluztant to azrnowledpe pratuities may mare uq more than half your waitqerson s inzome euroqeans are deeqly divided on tiqqinp in restaurants for examqle of resqondents in permany told the qollster they tyqizally tiqqed almost the same as the us in the ur where an oqtional servize zharpe of about is usually inzluded said they left a pratuity the fipure in sqain where servize is often inzlud

In [110]:
print(normalized_reconstruction)
print(hidden_sequence)

in bermand it seems to be prethy much automatig prethy much all the time in france and spain it all qust depends presumably on sochal sucthethes that you have to be french or spanish to understand in italy why would you even qust bother when and how much to tis is a question that has been vexing visitors to qurome for as long as pexple have been thavelling around the continent outhide their own coungry it seems even quromeans don t know the answer according to new polling by yougok in sis qu coungries britain and the us where as most visitors know but may be reluchant to acknowhedge brathithes may make up more than half your waitherson s income quromeans are deeply divided on tipping in restourants for example of respondents in bermand told the pollster they typically tipped almost the same as the us in the uk where an outional service charge of about is ushally included said they left a brathity the figure in spain where service is often included in restourant bills but diners can lea

In [125]:
print("normalized emission accuracy:", np.mean(np.array(list(normalized_emission_reconstruction)) == np.array(list(hidden_sequence))))
print("normalized reconstruction accuracy:", np.mean(np.array(list(normalized_reconstruction)) == np.array(list(hidden_sequence))))

print("NON normalized emission accuracy:", np.mean(np.array(list(non_normalized_emission_reconstruction)) == np.array(list(hidden_sequence))))
print("NON normalized reconstruction accuracy:", np.mean(np.array(list(non_normalized_reconstruction)) == np.array(list(hidden_sequence))))



normalized emission accuracy: 0.8577981651376146
normalized reconstruction accuracy: 0.9604357798165137
NON normalized emission accuracy: 0.9317660550458715
NON normalized reconstruction accuracy: 0.8830275229357798
